### ISSUE TITLE
Sequence type annotations

### ISSUE THREAD

**Issue by korikuzma** [biocommons/hackathon-2023#10]
### Submitter Name

Alex Wagner (@ahwagner)

### Submitter Affiliation

Nationwide Children's Hospital

### Requested By

seqrepo community

### biocommons Repo

seqrepo

### Project Details

sequence type as annotation: alphabet, double stranded, circular characteristics as examples. 

Original issue [here](https://github.com/biocommons/biocommons.seqrepo/issues/113). 
> It would be useful for supporting downstream methods (e.g. circular sequence support #70) to store some basic characteristics about a sequence at the sequence level. This MAY be accomplished by adding these annotations to the FASTA key fields.
> 
> I think we would minimally like to have:
> 
>     * [ ]  Sequence Alphabet (amino acid vs. nucleic acid)
> 
> 
> and in the event it is nucleic acid:
> 
>     * [ ]  circular / linear sequence
> 
>     * [ ]  single-stranded / double-stranded sequence
> 
> 
> To accomplish this @ccaitlingo and I discussed extending the `store` and `fetch` methods of FastaDir to add these annotations to FASTA keys, in the following format:
> 
> >{digest}|{aa / na}|{linear / circular}|{single / double}
> 
> or a compressed version of the above (i.e. bitflags). Making this issue for discussion and progress.

### Skill Level

Intermediate

### Required Skills

Python

**Comment by reece** [comment]
For reasons discussed in https://github.com/biocommons/biocommons.seqrepo/issues/113#issuecomment-1638679999, this project is being retracted.
