### ISSUE TITLE
triage hgvs issues

### ISSUE THREAD

**Issue by korikuzma** [biocommons/hackathon-2023#3]
### Submitter Name

Reece Hart (@reece)

### Submitter Affiliation

MyOme

### Requested By

hgvs community

### Lead(s)

@reece 

### biocommons Repo

hgvs

### Project Details

It is important for us to process issues in a timely manner, but doing so takes time. The goal for this project is to triage issues by commenting, escalating, or dismissing as appropriate.

### Skill Level

Intermediate

### Required Skills

Python, HGVS nomenclature

**Comment by korikuzma** [comment]
@reece @andreasprlic Would you be able to list some bug related issues that you'd like to see tackled?

**Comment by korikuzma** [comment]
@reece since this is being included as part of the agenda, can we close this and #7? Or did you still want them to be project ideas?

**Comment by reece** [comment]
Sure. Closing both.
